<link rel="stylesheet" href="{{ asset('front/css/open-iconic-bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('front/css/animate.css') }}">
<link rel="stylesheet" href="{{ asset('front/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('front/css/owl.theme.default.min.css') }}">
<link rel="stylesheet" href="{{ asset('front/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('front/css/aos.css') }}">
<link rel="stylesheet" href="{{ asset('front/css/ionicons.min.css') }}">
<link rel="stylesheet" href="{{ asset('front/css/bootstrap-datepicker.css') }}">
<link rel="stylesheet" href="{{ asset('front/css/jquery.timepicker.css') }}">
<link rel="stylesheet" href="{{ asset('front/css/flaticon.css') }}">
<link rel="stylesheet" href="{{ asset('front/css/icomoon.css') }}">
<link rel="stylesheet" href="{{ asset('front/css/style.css') }}">